### ISSUE TITLE
List Instances Check Should Ignore 'Terminated' Instances

### ISSUE THREAD

**Issue by recursivecodes** [aalmiray/oci-gradle-plugin#3]
The 'listInstances' check should ignore instances that have a lifecycle state of "Terminated".

https://docs.cloud.oracle.com/en-us/iaas/tools/java/1.15.3/com/oracle/bmc/core/requests/ListInstancesRequest.html

https://github.com/kordamp/oci-gradle-plugin/blob/8aba3ef098e90c8a3fb266c95424db3699a0c2cd/plugins/oci-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/oci/tasks/create/CreateInstanceTask.groovy#L249

**Comment by aalmiray** [comment]
Fixed with https://github.com/kordamp/oci-gradle-plugin/commit/b87b9478c60515520130d24d6f2663252b35f5d7
